import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { ScanReport } from "@/types/scan";
import { formatDuration } from "./input-validator";

export function generatePdfReport(report: ScanReport, scanId: string): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Header
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, pageWidth, 40, "F");
  
  doc.setTextColor(6, 182, 212);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("SecFlow", 20, 25);
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("Vulnerability Assessment Report", pageWidth - 20, 25, { align: "right" });
  
  // Reset colors
  doc.setTextColor(0, 0, 0);
  
  let yPos = 55;
  
  // Scan Info Section
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Scan Information", 20, yPos);
  yPos += 10;
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  
  const scanInfo = [
    ["Scan ID", scanId],
    ["Target Scope", report.scope],
    ["Duration", formatDuration(report.duration_seconds)],
    ["Subdomains Found", report.counts.subdomains.toString()],
    ["URLs Discovered", report.counts.urls.toString()],
    ["Hosts Scanned", report.counts.hosts.toString()],
    ["Open Ports", report.counts.open_ports.toString()],
  ];
  
  autoTable(doc, {
    startY: yPos,
    head: [],
    body: scanInfo,
    theme: "plain",
    styles: { fontSize: 10 },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 50 },
      1: { cellWidth: 100 },
    },
    margin: { left: 20 },
  });
  
  yPos = (doc as any).lastAutoTable.finalY + 15;
  
  // Hosts & Ports Section
  if (report.nmap_results.length > 0) {
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Discovered Hosts & Services", 20, yPos);
    yPos += 10;
    
    const hostsData = report.nmap_results.flatMap((host) =>
      host.ports.map((port) => [
        host.host,
        port.port.toString(),
        port.state,
        port.service,
        port.version || "-",
      ])
    );
    
    autoTable(doc, {
      startY: yPos,
      head: [["Host", "Port", "State", "Service", "Version"]],
      body: hostsData,
      theme: "striped",
      headStyles: { fillColor: [6, 182, 212], textColor: [15, 23, 42] },
      styles: { fontSize: 9 },
      margin: { left: 20, right: 20 },
    });
    
    yPos = (doc as any).lastAutoTable.finalY + 15;
  }
  
  // AI Summary Section
  if (report.ollama_summary) {
    // Check if we need a new page
    if (yPos > 220) {
      doc.addPage();
      yPos = 20;
    }
    
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("AI Risk Analysis", 20, yPos);
    yPos += 10;
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    
    // Split text to fit page width
    const splitText = doc.splitTextToSize(report.ollama_summary, pageWidth - 40);
    doc.text(splitText, 20, yPos);
  }
  
  // Footer
  const pageCount = doc.internal.pages.length - 1;
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Generated by SecFlow | Page ${i} of ${pageCount} | ${new Date().toLocaleString()}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    );
  }
  
  doc.save(`secflow-report-${scanId}.pdf`);
}
